### ISSUE TITLE
Cannot detect swipe 

### ISSUE THREAD

**Issue by zohaibbrohi** [ariok/BWWalkthrough#68] opened 2016-08-30 12:15 UTC
Hi, I want to detect swipe so i can restrict some views, for example i have 10 pages and i dont want swipe to work on number 4 page (on page 4 I only want to use button for swipe for swipe gesture)

**Comment by ariok** [comment] 2016-09-01 15:46
This feature is not an intended behaviour of the library actually :(  and it is kind of confusing in my opinion. I close the issue since I'm not going to include this feature, anyway you can access the `scrollview` object of `BWWalkthroughViewController` and implement this logic :)

**Closed by ariok** 2016-09-01 15:46 UTC

**Comment by zohaibbrohi** [comment] 2016-09-01 15:53
yeah, I used walkthrough!.scrollview.scrollEnabled = false, And its restricting the view not to be scroll to next page now i want to enable it on button click. I will figure it out. Thanks
