### ISSUE TITLE
Could not cast to BWWalkthroughViewController

### ISSUE THREAD

**Issue by croossin** [ariok/BWWalkthrough#52] opened 2016-04-07 19:44 UTC
Could not cast value of type 'UIViewController' (0x1094ff5e0) to 'BWWalkthrough.BWWalkthroughViewController' (0x10734ab50).

I have made sure I imported BWWalkthrough and declared the delegate.  But I keep getting this error on line:

`walkthrough = stb.instantiateViewControllerWithIdentifier("container") as! BWWalkthroughViewController`

I have ensured that the it is in fact a BWWalkthroughViewController in interface as well.

EDIT: 
I have noticed that this error is thrown when I use CocoaPods to install BWWalkthrough - not when I include the files manually....

**Comment by FabianGroeger96** [comment] 2016-04-11 17:22
I have the same error, i really hope it get's fixed fast...

**Comment by vinnyoodles** [comment] 2016-04-19 17:35
You have to set the module in the interface builder to `BWWalkthrough`. It's basically importing the pod into your interface builder

**Comment by ariok** [comment] 2016-04-27 13:37
@croossin can you confirm that what @vinnyoodles works? I cannot reproduce the issue you are reporting...

**Comment by vinnyoodles** [comment] 2016-04-27 16:52
![screen shot 2016-04-27 at 12 51 24 pm](https://cloud.githubusercontent.com/assets/8698599/14860447/e3668fd4-0c76-11e6-971f-1cde328d8949.png)


![screen shot 2016-04-27 at 12 51 38 pm](https://cloud.githubusercontent.com/assets/8698599/14860448/e3690098-0c76-11e6-8f5d-b006f36e907c.png)

The first picture is what was causing my error, the second picture is what I did to fix it. Hope that helps

**Comment by ariok** [comment] 2016-05-03 07:48
Thanks! I've tried what @vinnyoodles suggested, it worked for me too. I close the issue.

**Closed by ariok** 2016-05-03 07:48 UTC
