### ISSUE TITLE
cocoapods support?

### ISSUE THREAD

**Issue by shams-ahmed** [ariok/BWWalkthrough#19] opened 2015-05-31 14:32 UTC
are you planning to add cocoapods support?

**Comment by ariok** [comment] 2015-05-31 20:51
Absolutely! At the moment I cannot work on this project, anyway is one of the next steps to improve the component.

**Comment by XBeg9** [comment] 2015-08-20 19:00
@shams-ahmed temporary you can use 

`pod 'BWWalkthrough', :git => 'https://github.com/XBeg9/BWWalkthrough.git', :branch => ‘fs/podspec'
`

**Comment by shams-ahmed** [comment] 2015-08-20 19:10
@XBeg9 ill try this approach!

**Comment by ariok** [comment] 2015-11-22 14:08
Just a quick note on this issue. I'm willing to include Cocoa Pods support to BWWalkthrough, I've already worked on that but I had some configuration problems... anyway, I'm planning to fully support Cocoa Pods until the end of January 2016.

**Comment by shams-ahmed** [comment] 2015-11-22 14:57
thanks!

**Comment by michaelbina** [comment] 2015-12-13 04:56
@XBeg9 FYI - I'm getting this error while using your branch with cocoa pods:

[!] Unable to read the license file `/Users/michaelbina/Library/Mobile Documents/com~apple~CloudDocs/Projects/white rabbit/dev/ios/Pods/BWWalkthrough/LICENSE.txt` for the spec `BWWalkthrough (0.6.1)`

I think the problem is simply that the license file needs to be titles LICENSE.txt in all caps as opposed to License.txt which is how you have it.

**Comment by ariok** [comment] 2016-02-01 07:36
I'm trying to add CocoaPods support but I'm still failing! I'm reading this guide: 
https://guides.cocoapods.org/making/making-a-cocoapod.html 
and this:
https://guides.cocoapods.org/making/using-pod-lib-create
The main problem is that the example project cannot recognize the BWWalkthrough classes. Any hint?

**Comment by andreamazz** [comment] 2016-02-01 08:40
Add a Podfile to your example project with this inside:
```
pod 'BWWalkthrough', path: '../'
```
run `pod install`, the pod will be integrated in the sample as "Development pods".

**Comment by ariok** [comment] 2016-02-02 15:32
Fixed with version 1.0.1 https://github.com/ariok/BWWalkthrough/releases/tag/1.0.1

**Closed by ariok** 2016-02-02 15:32 UTC
Labels: enhancement
