### ISSUE TITLE
ScrollView not scrolling with next/prev buttons, even though nextPage() is getting called.

### ISSUE THREAD

**Issue by joshhensley** [ariok/BWWalkthrough#65] opened 2016-07-25 16:25 UTC
I have configured BWWalkthough using storyboard, as the example project does. Everything works great. But I can't seem to get the nextButton/prevButton to work. The IBOutlets are connect properly and the nextPage() action is called. The delegate even receives walkthroughNextButtonPressed/walkthroughPrevButtonPressed calls. The actual scrolling never occurs though. Any thoughts?

I am using a subclass of BWWalkthroughViewController as follows:
`class WelcomeWalkthroughViewController: BWWalkthroughViewController, BWWalkthroughViewControllerDelegate { ... }`

**Comment by ariok** [comment] 2016-07-28 08:50
@joshhensley I'm going to check it in a couple of days. Can you try the example please? does it work for you?

**Comment by marciliojrs** [comment] 2016-08-01 18:27
Hi guys, I had a similar problem trying to call `nextPage` from my controller. I resolved it updating `gotoPage` method on `BWWalkthroughViewController`. 

I replaced this line:
`scrollview.scrollRectToVisible(frame, animated: true) `
for this one:
`scrollview.setContentOffset(frame.origin, animated: true)`

**Comment by ariok** [comment] 2016-10-01 07:21
I'm not able to reproduce the issue :/

**Comment by ariok** [comment] 2016-10-14 07:43
2 months without answers. I close the issue since I cannot reproduce it.

**Closed by ariok** 2016-10-14 07:43 UTC
Labels: help wanted
