### ISSUE TITLE
Scrollview can be drag all around

### ISSUE THREAD

**Issue by RonGafni** [ariok/BWWalkthrough#86] opened 2016-12-31 07:42 UTC
Hey,

I'm trying to fix a problem with my scrollview. I want the scrollview move only right and left(without the option to be drag up or down). 

How can i fix it?

**Comment by SeRG1k17** [comment] 2017-01-04 21:45
more info pls

2016-12-31 10:42 GMT+03:00 RonGafni <notifications@github.com>:

**Comment by ariok** [comment] 2017-02-04 07:16
@RonGafni  actually the scrollview should only move left and right. Are you experiencing a different behaviour? please provide more info as @SeRG1k17 already suggested.

**Comment by RonGafni** [comment] 2017-02-04 14:17
@ariok Yes, I can drag the view around. I need to "lock" the view and just move right and left.

**Comment by apiejh** [comment] 2017-02-05 10:08
@RonGafni are you using autolayout? If so, please make sure you are not using explicit sizes and instead use proportions to resize your views. Perhaps one of your views receives height larger than the scrollview and this causes vertical scrolling?

**Comment by jpodcedensek** [comment] 2017-02-08 15:32
@RonGafni are you using your walkthrough container within a UINavigationController? If so, you need to set `automaticallyAdjustsScrollViewInsets` to false.

**Comment by ariok** [comment] 2017-05-22 21:10
I close the issue since I cannot reproduce it. Please feel free to open it again providing more information.

**Closed by ariok** 2017-05-22 21:10 UTC
Labels: help wanted
