### ISSUE TITLE
bwwalkviewcontroller page will backward to its parent issue

### ISSUE THREAD

**Issue by LouiLu** [ariok/BWWalkthrough#34] opened 2015-11-05 23:31 UTC
Hi Ariok,
I am a leaner of Swift and I am currently using bwwalkthrough. It works properly instead when the bwwalkthroughviewcontroller page(the main page) loads, if I tap on the upper half of the view, it will accidentally backward segue to its previous page and never shows again. 

Here provides the repo url: git@github.com:evtechnologies/Wave.git

Thanks for help.

Loui

**Comment by ariok** [comment] 2015-11-07 09:36
Interesting! I'll check your project!

**Comment by ariok** [comment] 2015-11-07 09:37
ops... I erroneously closed it.

**Comment by ariok** [comment] 2015-11-07 09:58
it's something really really strange. If you change the animation from Cross Dissolve to a Standard Vertical cover it works without problem. I don't know how to help you more... I just suggest to change the animation to the Standard Vertical for now.

**Closed by ariok** 2015-11-07 09:58 UTC
Labels: help wanted

**Comment by ariok** [comment] 2015-11-07 10:04
The problem is the Partial Curl. The top area of a view controller presented via Partial Curl automatically is automatically connected with a dismiss action. You need to change the presentation style to avoid this issue... try Vertical Cover presentation style. 

(I admit that I didn't know about this "feature" of the Partial Curl... and I cannot even find it documented, but I see a lot of people reporting it more like a bug...)
