### ISSUE TITLE
Could not cast value of type 'BWWalkthrough.BWWalkthroughViewController' BWWalkthroughViewController'

### ISSUE THREAD

**Issue by ricardosobral** [ariok/BWWalkthrough#56] opened 2016-05-22 23:03 UTC
So I have followed your tutorial step by step. Still having issues...

I have installed it first with CocoaPods and seems that others are having the same issue.

If I name the custom class module (top right on the identity inspector) BWWalkthrough it will crash with the following:
Could not cast value of type 'BWWalkthrough.BWWalkthroughViewController' (0x1054e6b50) to 'NameOfMyProject.BWWalkthroughViewController'

If I change the custom class module to NameOfMyProject (or leave it blank) it does not crash and the initial View Controller loads fine, when I tap the first button it simply does not load step0, the code executes fine, but nothing happens and I never get to see the first BWWalkthroughViewController.

I have tried with both cocoaPods and by copying the files. Spent a good two hours looking at this and got nowhere. Please help!!!!!

**Comment by ariok** [comment] 2016-05-23 07:23
Can you try to import the library manually and letting me know if you encounter the problem? I'd like to know if is related to Cocoa Pods only, since I cannot reproduce the issue. To import BWWalktrough just drag and drop in your project swift files from the Class folder Pod/Classes.

**Comment by ricardosobral** [comment] 2016-05-23 21:11
I have done that and found the same issue unfortunately.

**Comment by JPROFFICIAL** [comment] 2016-05-29 22:48
@ricardosobral I had this same issue with the casting not completing and crashing the project. I searched the closed issues, and found this 
![screen shot 2016-05-29 at 5 47 15 pm](https://cloud.githubusercontent.com/assets/14960440/15636473/83f7730c-25c5-11e6-8a5e-bb4aaa21fd54.png)

This fixed the error for me and all works as expected. Did this help?

**Comment by ariok** [comment] 2016-06-10 11:58
I close the issue since the solution proposed by @JPROFFICIAL seems to fix this issue (thank you! :))  Plus, I see that with Xcode 7.3.1all the BWWalkthrough classes are correctly recognized by IB (sometimes you have to select and deselect the identity inspector class textfield though).

**Closed by ariok** 2016-06-10 11:58 UTC
